### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by StellaSmith** [StellaSmith/pervybot-rs#14]
Create a Dockerfile which should contain the following:
- The compiled binary
- Any required configuration file
- ffmpeg
- yt-dlp
When using the filesystem for storage instead of a database, make sure to use a subdirectory in order to create an storage volume

**Comment by elfein727** [comment]
All current requirements should be met by #15

**Comment by StellaSmith** [comment]
Fixed in #15
